name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: run lint
      run: |
        pip install tox poetry tox-poetry
        tox -e lint
